spring:
  # 스프링 앱과 h2와 연결하겠음
  datasource:
    url: jdbc:h2:tcp://localhost/~/colorMeeting
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate: # jpa connection pool은 hibernate를 활용하겠음
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
logging.level:
  org.hibernate.SQL: debug